### ISSUE TITLE
toctree in code contributions

### ISSUE THREAD

**Issue by ifranda** [NCAR/VaporDocumentationWebsite#13]
It looks like there's a toctree in docs/contributingToVapor/codeContributions.rst that doesn't lead anywhere, so it creates a dropdown with no subpages. Should we remove this section or replace it with something new?

```
Adding to the Code Base
-----------------------

After successfully compiling Vapor, you can make changes to the code base.  Make sure to follow Vapor's `Code Conventions <https://github.com/NCAR/VAPOR/wiki/Vapor-Coding-Convention>`_.  If building on a UNIX system, eliminate all compiler warnings.

What pieces of code you add or modify will depend on the issue you're trying to fix.  Most often, contributors will be doing one of two things:

.. toctree::
   :maxdepth: 1

   createDataReader
   createRenderer

Build and Test an Installer
---------------------------
```

**Comment by ifranda** [comment]
@sgpearse Is what this is trying to say still relevant or should we remove it entirely?

**Comment by sgpearse** [comment]
This was work that was going to be done at some unknown time in the future, but IMO the effort behind this is large compared to the payoff.  Pinging @stasj and @NihanthCW for their opinions.

My opinion is to delete it, and reassess if this is something that's valuable to the project.

**Comment by NihanthCW** [comment]
I would say- we leave it there for the future.
