### ISSUE TITLE
Documentation to add conda-forge channel when installing pythonAPI from .tar.bz

### ISSUE THREAD

**Issue by sgpearse** [NCAR/VaporDocumentationWebsite#21]
We cover the step for adding conda-forge in our "[Building the conda image](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#building-the-conda-image)" portion of our docs, which not everybody is necessarily doing.  It needs to be added to the "[Installing the conda image](https://ncar.github.io/VaporDocumentationWebsite/contributingToVapor/codeContributions.html#installing-the-conda-image)" section.  Something like the following, before step 5:

```
If you have not done so already, ensure that you have added the conda-forge channel:
conda config --add channels conda-forge
```

**Comment by ifranda** [comment]
I can slip this into the documentation PR I have open
